version: "3.9"

services:
  app:
    build: .
    container_name: license_plate_app
    ports: 
      - 8000:8000
    links: 
      - db
    depends_on:
      - db
  db:
    image: postgres:16.3
    container_name: license_plate_postgres_db
    environment:
      - POSTGRES_USER=haidisiz
      - POSTGRES_PASSWORD=e0Y55HVL2OfnKaOIzRFY-vJQ_snKQ1fu
      - POSTGRES_NAME=haidisiz
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./license_plate_db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  volume_name:
    name: license_plate_db
